name: LearnAsYouGoEmulator-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - emcee=2.*     # Example is not compatible with emcee 3.*
  - scipy

  # Development
  - pre-commit
  - black
  - isort
  - mypy
